version: '2'

services:
  master:
    image: crossz/redis-sentinel-distributed
    network_mode: "host"
    environment:
      - APPENDFSYNC=everysec
      - REQUIREPASS=12345678
      - CLIENTPORT=6479
      - CLIENTHOST=localhost
      - MASTERHOST=
      - MASTERPORT=
    volumes:
      - "/tmp/6479:/data"
      
  slave:
    image: crossz/redis-sentinel-distributed
    network_mode: "host"
    environment:
      - APPENDFSYNC=everysec
      - REQUIREPASS=12345678
      - CLIENTHOST=localhost
      - CLIENTPORT=6579
      - MASTERHOST=localhost
      - MASTERPORT=6479
    volumes:
      - "/tmp/6579:/data"